apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmfrontend-test
  namespace: vm-project-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmfrontend-test
  template:
    metadata:
      labels:
        app: vmfrontend-test
    spec:
      containers:
        - name: vmfrontend-test
          image: gcr.io/cubs-consulting/frontend-repository/frontend-vima
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
      - name: frontend-rcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vmfrontend-test-nodeport
  namespace: vm-project-test
spec:
  selector:
    app: vmfrontend-test
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vmfrontend-test-ingress
  namespace: vm-project-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
spec:
  tls:
  - hosts:
    - rancher-vmfrontend-test.citwdd.net
    secretName: vmfrontend-test-tls
  rules:
  - host: rancher-vmfrontend-test.citwdd.net
    http:
      paths:
      - backend:
          serviceName: vmfrontend-test-nodeport
          servicePort: 80
    
      
