apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmfrontend-dev-deploy
  namespace: vima-project-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmfrontend-dev-deploy
  template:
    metadata:
      labels:
        app: vmfrontend-dev-deploy
    spec:
      containers:
        - name: vmfrontend-dev-deploy
          image: gcr.io/cubs-consulting/vmfrontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
      - name: frontend-rcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vmfrontend-dev-nodeport
  namespace: vima-project-dev
spec:
  selector:
    app: vmfrontend-dev-deploy
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmfrontend-dev-ingress
  namespace: vima-project-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
spec:
  tls:
  - hosts:
    - rancher-vmfrontend-dev.cit.byui.edu
    secretName: vmfrontend-dev-tls
  rules:
  - host: rancher-vmfrontend-dev.cit.byui.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vmfrontend-dev-nodeport
            port:
              number: 80
    
      
